### ISSUE TITLE
Direcionar todas as rotas para o index.html

### ISSUE THREAD

**Issue by luskas8** [luskas8/card-game#11]
Além disso, acho melhor servir o index.html direto no '/' e todas as demais rotas devem ser redirecionadas para o '/' de modo que o cliente não consiga ter acesso ao código fonte através do navegador.

_Originally posted by @freirart in https://github.com/luskas8/card-game/issues/10#issuecomment-1752889463_

**Comment by freirart** [comment]
Resolvido com o PR https://github.com/luskas8/card-game/pull/19
